### ISSUE TITLE
Adjust floor for saturation and brightness possible?

### ISSUE THREAD

**Issue by rostar99** [NiklasReiche/ad-spotify-mood-lights-sync#9]
I have several bulbs that vary in saturation and brightness when in color mode (values are too low). As a workaround, I have an automation that takes the hs_color that the app outputs and adds to these values, and turns on the light again with the new settings.  Obviously, there is a noticeable transition to the final color. Could this be accomplished with color profiles by setting a minimum for saturation and brightness with the hue left as is? If not, could I set a floor for these values in the app itself (py code)?

**Comment by NiklasReiche** [comment]
No, something like this is currently not really possible. While you could change the color profile's sample points, I doubt you would reliably achieve the desired effect. The problem is that all interpolation calculations are done in RGB space, which doesn't translate well to the HSV parameters for the lights.

I'm not really satisfied with the current interpolation model myself and I think it would be a good idea to switch to an HSV space interpolation instead. Then the color profile would be defined by HSV sample points and there should be no unexpected variation in saturation and brightness for interpolated values. I'll look into implementing this HSV mode and compare the results.

**Comment by rostar99** [comment]
NiklasReiche, I just noticed the change in the configuration file when I was reinstalling after appdaemon update changed the config folder. The new change works well enough to turn off the automation workaround I wrote last year. Thank you.
